### ISSUE TITLE
(Bug) At some locales, the song starts at 10x speed

### ISSUE THREAD

**Issue by lucaspontoexe** [EliteAsian123/YARG#10]
The bottom right input field that specifies the song speed starts with a "1.0" value.
At some countries, the comma is used as the decimal separator, making the parser think the song should start at 10x speed.

![image](https://user-images.githubusercontent.com/25611847/224451364-d630c04f-adcc-4afd-acd3-6a341c9bb783.png)

see also: https://en.wikipedia.org/wiki/Decimal_separator

**Comment by EliteAsian123** [comment]
*Darn localization*... I'm kidding.

Good catch, I'll probably have to make some sort of language feature for this. I'm assuming that this doesn't actually mess with any logic (please let me know if it does), but it is something that will be addressed in the near future.

Thanks, and congrats on creating the first issue for this project!
