### ISSUE TITLE
(Roadmap) .chart Support

### ISSUE THREAD

**Issue by EliteAsian123** [EliteAsian123/YARG#13]
Add .chart format support for songs.

**Comment by NicJellz** [comment]
Not sure if this is relevant - but there is a C# implementation of converting .mid files to .chart files available here:

https://github.com/raphaelgoulart/mid2chart

Not sure if .chart files would have full instrument support however (especially vocals), but maybe in later games?

**Comment by EliteAsian123** [comment]
> https://github.com/raphaelgoulart/mid2chart

Thanks for pointing me to this, I'll take a look at it!

> Not sure if .chart files would have full instrument support however (especially vocals), but maybe in later games?

This is probably the main reason why I haven't added support yet. As far as I'm aware, `.chart` doesn't have pro instrument support and harmonic vocal support. That being said, a lot of custom songs are in the format, so I definitely want to add support for it in the near future.

**Comment by lucaspontoexe** [comment]
This repo may be useful as well: 
https://github.com/TheNathannator/GuitarGame_ChartFormats/tree/main/doc/FileFormats/.chart

**Comment by EliteAsian123** [comment]
> This repo may be useful as well: https://github.com/TheNathannator/GuitarGame_ChartFormats/tree/main/doc/FileFormats/.chart

Yes, @TheNathannator's work is very helpful.

**Comment by EliteAsian123** [comment]
Added in v0.10.0!
