### ISSUE TITLE
Open note HOPOs are replaced with strums

### ISSUE THREAD

**Issue by archwk100** [EliteAsian123/YARG#142]
Open note HOPOs don't exist and are always replaced with open strum notes.

**Comment by NarrikSynthfox** [comment]
Open note hopos are always forced right, never done automatically? I'll probably be able to fix this pretty easily.

**Comment by raphaelgoulart** [comment]
Maybe having this as a separate issue is better, but this is already mentioned in https://github.com/EliteAsian123/YARG/issues/2

**Comment by raphaelgoulart** [comment]
Implemented in pull request https://github.com/EliteAsian123/YARG/pull/162, will apparently be merged to master once there are graphics for it (currently being worked on)

**Comment by EliteAsian123** [comment]
This has now been added! Will be released in the next update.
