### ISSUE TITLE
Beatles Hofner Bass + Chinese 360 Wireless Receiver not responsive

### ISSUE THREAD

**Issue by leberj** [EliteAsian123/YARG#19]
Has anyone else had this issue, either with the Chinese wireless dongle or with the Hofner bass specifically? I opened YARG, had my guitar synced and it wouldn't recognise the controller/receiver in the 5 fret controller options. I plugged in a Wii Les Paul using a crappy Wii > USB cable and it detected the guitar immediately. Re-synced the Hofner and it didn't work, but it worked in Clone Hero straight away.

There's no serial number or anything on the receiver but I can give you the hardware IDs if that helps:
VID_045E&PID_02A9&REV_060

**Comment by leberj** [comment]
Awesome, glad I can help in any way. Happy to test this again whenever you have a chance to implement any changes or adjustments. No pressure, I have 20+ guitars but only 1 Hofner so I'll manage lol

**Comment by EliteAsian123** [comment]
20+ guitars? Damn, that's a lot.

I am thinking of finishing vocal combos today, and re-doing the “EDIT PLAYERS” screen tomorrow, along with (hopefully) a fix for unsupported devices. It is a little bit difficult to diagnose the issue as all of my devices are supported, but I think I may have an idea to make it work.

Apologies for keeping you waiting, and thanks again for the very kind donation!

**Comment by leberj** [comment]
I posted my collection on reddit once but it's increased since then. Mainly because I'm trying to salvage broken ones into fully functional guitars. Some are just combining bits and pieces from others to make 1 working, some have been arduino modded and upgraded to mechanical fret switches, so it's for a purpose but it's slow going.

No worries at all for the unsupported devices, it shouldn't impact me too much but I know a lot of people do go for the cheaper third party dongles, judging from reddit posts. Once you implement the fix I'll give it a whirl, again no pressure on this, I just wanted to see if anyone else had the same issue.

Not a problem on the donation, I'm sure I'll play this as much as Clone Hero, if not more, so I'm happy to chip in where I can.

**Comment by EliteAsian123** [comment]
Hello! I've created an updated version of the game that *may* fix the issue. The link for it can be found here:
https://drive.google.com/file/d/1DcKNyK-E-_w1NBM9AgaFBTPP0JFXw9xS/view?usp=share_link

It contains the newest dev-build that has a completely new “Add/Edit Players” menu.

To add an unsupported device:
1. Click “Add/Edit Players” on the main menu.
2. Click “Add Player.”
3. Find the device in the list. It should say “NOT RECOGNIZED” beside it. Click on it.
4. The device should now appear as recognized. Click on it again.
5. Choose input strategy (probably “Five Fret”). Press “Next.”
6. See if you can bind everything. **I have my doubts that this will work**, but it is worth a shot.
7. If you can bind everything, please let me know and have fun! If not, also please let me know. Thanks.

**Comment by EliteAsian123** [comment]
Okay, so I know that this issue was posted first, but the newer issue (#20)  has more info on it, so I'm going to mark *this* as a duplicate and close it.

I apologize if this offends you in any why; you *are* the first to point this out to me.

Thanks.
