### ISSUE TITLE
black screen with a gray rectangle in the middle after selecting "Quick Play"

### ISSUE THREAD

**Issue by SkullMan140** [EliteAsian123/YARG#21]
upon selecting the "Quick Play" option, nothing happens other than a black screen with a gray rectangle in the middle, and can't do anything in the game

**Comment by EliteAsian123** [comment]
Thanks for the issue report.

Did you select a proper song folder (with songs in it) in the settings? If so, and the song folder is large, what the game is doing is creating a cache. I should probably add some sort of indicator that the game is doing something. Depending on your hardware, this could take a while, especially the first step.

This is on me for not indicating loading, and I apologize for the inconvenience.

If you are still unable to load the game after selecting a proper song folder, please re-open the issue. Thanks!
