### ISSUE TITLE
issues binding Wii Harmonix guitar on a Mac

### ISSUE THREAD

**Issue by Jimmy5651** [EliteAsian123/YARG#232]
Hi again! This newest update is awesome, and I'm looking forward to being able to play on my Mac.

I'm having issues binding the buttons on my Wii Harmonix guitar though. None of the frets are registering — the only buttons registering at all are the plus and minus (which it names "Blue Fret" and "Green Fret") and the little knob thing on the bottom (which it names "Whammy"). 

I was able to get the same guitar working on Windows. Wondering if there's something I'm screwing up this time around? Thanks!

**Comment by TheNathannator** [comment]
Okay what the heck Unity lol

I can only assume the input system isn't being consistent about report IDs across platforms, that'll make the control layout be off by 1 byte.

This exact scenario has already happened on Linux, so I already know how to fix it. I'll try to get it fixed before v0.10 releases properly.

**Comment by Jimmy5651** [comment]
Awesome, appreciate you!

Having similar problems binding my Arduino guitar FWIW — guessing it's the same Unity control layout issue.

This is gonna be dope tho, love how you can use an iPhone as a mic on the Mac version. Thanks again
