### ISSUE TITLE
(Bug) Songs list is blank if I change to another songs folder

### ISSUE THREAD

**Issue by SkullMan140** [EliteAsian123/YARG#24]
sorry for being a pain in the ass with all the issues 😅, but i found another problem

i used to have a songs folder with only 3 songs for testing stuff, but i decided to change the songs location to a folder with more songs and.... even when i use the "refresh cache" option, the songs list is blank, it just says "Song Name - Artist - No Score - 1:23 - Custom" and "..." where the album cover should be, i waited for an hour and restarted the game multiple times, but it just don't show any song in the list

(yes, i got the 0.3.4 build)

**Comment by EliteAsian123** [comment]
No problem with the issues! I'm glad as this allows me to polish the game and fix up common issues.

Can you go to the selected directory and find the `yarg_cache.json` file, and send it to me by attaching a file to your next comment on this issue? This will help me narrow down the issue, as I don't have enough information to help you at the moment.

Thanks!

**Comment by SkullMan140** [comment]
for some reason it don't let me send the json file, but i noticed every time i open the game, it puts as default my old folder where i got the songs for testing, and even if i delete the cache and scores json files, it re-creates them in that old folder instead of the new one, don't know if it has anything to do with my issue

**Comment by EliteAsian123** [comment]
Okay. I think I found the issue. I'll let you know if I fix it, thanks for the help.

**Comment by EliteAsian123** [comment]
Yup. The issue was a `!=` instead of a `==`. Hotfix will be released soon. Thanks!
