### ISSUE TITLE
Drum Pad Scrolling

### ISSUE THREAD

**Issue by EmperorJacoba** [EliteAsian123/YARG#241]
The yellow pad and blue pad should allow for scrolling through the menus. 
Yellow pad should scroll up, Blue pad should scroll down in the menus.

**Comment by TheNathannator** [comment]
This is already implemented, though it might be in the beta (v0.10.0b) and not the stable release (v0.9.1).

**Comment by EmperorJacoba** [comment]
Ah, then drum pad scrolling just doesn't work in the MAIN menu then. It does work in the quickplay menu, my mistake.

**Comment by TheNathannator** [comment]
Yeah, controller navigation isn't implemented for the main menu yet, it's just the song list currently. Hopefully that can be handled sometime soon!
