### ISSUE TITLE
Start button for Drums

### ISSUE THREAD

**Issue by EmperorJacoba** [EliteAsian123/YARG#242]
When mapping a drum controller, there should be an option for a "Start" bind. Would not be required when mapping, but would be a helpful option for those with an extra drum switch.

(For personal context, I use my hi-hat pedal to pause the game mid-song in Clone Hero and a similar option here would be useful)

**Comment by TheNathannator** [comment]
I implemented this recently, it should be available in the next release. (I added it after the v0.10 beta was made so it's not currently in any released builds.)

**Comment by EmperorJacoba** [comment]
Coolio!
