### ISSUE TITLE
JSON for Ouvertbot

### ISSUE THREAD

**Issue by Lynekiboo** [EliteAsian123/YARG#25]
I tried with a custom song for rb3 and that work good, i saw for cache is a json file, so i use with Ouvertbot (a bot for request songs for clone hero) and that works except, we don't have the artist, album, genre and the charter

Is it in your plans that the cache file have info for the Ouvertbot ? that would be really great!

![image](https://user-images.githubusercontent.com/101982826/225802313-314b9e5b-7f04-4072-8665-1dae7281a2a8.png)

**Comment by EliteAsian123** [comment]
Hello!

I've never heard of Ouvertbot but I can (most likely) add support for it very easily.

Thanks for the suggestion!

**Comment by EliteAsian123** [comment]
Hello! I've officially added Ouvert support in fcef602. This feature will be included in the next update (which will be later today). Once released, go into the settings and click on "Generate OuvertBot Song List" and it will create a `json` file for you!

Thanks for the suggestion.
