### ISSUE TITLE
Settings Saving

### ISSUE THREAD

**Issue by mcjojo3** [EliteAsian123/YARG#26]
Heya, noticed that players aren't saved on quit, is this intended? Like is it just not implemented yet?

**Comment by EliteAsian123** [comment]
Hi!

Unfortunately, this is not implemented yet, but it is most definitely planned. I will keep this issue open as a reminder to me :)

Apologies for any inconveniences.

**Comment by mcjojo3** [comment]
Sounds good, love the progress soo far. Also quick question, are longer highway settings planned?

**Comment by EliteAsian123** [comment]
Thanks! Yup, full customizability of everything is planned! That comes later, though, unfortunately.

**Comment by mcjojo3** [comment]
Awesome, I love the progress and the constant updates so far! Keep it up!

**Comment by EliteAsian123** [comment]
Thanks for the kind words! I'm trying to update as much as possible right now, and I'm glad that people like that. I've been needing a whole new settings system for a while now, so I'll probably need to get started on that sooner or later. Thanks again!

**Comment by EliteAsian123** [comment]
Basic settings now save in e4e855551abd5d13523117cff4145a038d9bee66. Input bindings next!

**Comment by EliteAsian123** [comment]
Binds now save in dd86abbf4c8c3d9a12f61fdbf11b0780da439506. Due to technical constraints, players will not save *for now*, but the binding part does save making it a lot easier.
