### ISSUE TITLE
Is the 3 drum and 2 cymbal peripheral drums going to be supported?

### ISSUE THREAD

**Issue by mcjojo3** [EliteAsian123/YARG#28]
Hello again! I was just wondering if the 3 drum and 2 cymbal peripheral is going to be supported? I know this program is mainly focused on Rockband peripherals but as I only have that drum set at home it would be fun if that were to be an option although I understand if not!

**Comment by EliteAsian123** [comment]
Yes, it is planned! Unfortunately I do not have access to those peripherals, so I cannot test it.

**Comment by mcjojo3** [comment]
Glad to hear, I'll make sure to test it once its added!

**Comment by EliteAsian123** [comment]
*Should,* be working in the new update!
