### ISSUE TITLE
Pause feature

### ISSUE THREAD

**Issue by mcjojo3** [EliteAsian123/YARG#32]
I figure this is already planned but was wondering if it's in the works and in that case how the progress is on it?

**Comment by EliteAsian123** [comment]
You can currently press space to pause the game, although it is kind of scuffed. The pause menu is planned to be improved.

**Comment by mcjojo3** [comment]
Oh actually, I reopened this issue to ask if keybinded pause for peripherals is planned? As rn I emulate a controller button as space which works but requires some setup.

**Comment by EliteAsian123** [comment]
Yes, I plan to do this in the next update (today or tomorrow).

**Comment by EliteAsian123** [comment]
Forgot to close this issue.
