### ISSUE TITLE
(Bug) Game freezes causing desyncing

### ISSUE THREAD

**Issue by SkullMan140** [EliteAsian123/YARG#37]
i just got the most recent version to try it out, and i noticed the game have some moments where it freeze for a second, then continues, but when it continues the song gets out of sync, making it to not pair with the music

i tried it on vocals and guitar so far, but i guess the issue would be the same on drums

(as a side note, my PC is veery low end, so that might be a problem on my end lol)

**Comment by EliteAsian123** [comment]
Although the freezing probably can't be fixed (other than the “Low Quailty Mode”), the desync *may* be fixed by the “Use Audio Time” setting. Please try it, and see if it solves any issues.

**Comment by SkullMan140** [comment]
> Although the freezing probably can't be fixed (other than the “Low Quailty Mode”), the desync _may_ be fixed by the “Use Audio Time” setting. Please try it, and see if it solves any issues.

it seems that worked to solve the issue, thanks :D

**Comment by EliteAsian123** [comment]
No problem!
