### ISSUE TITLE
Disco Flipping

### ISSUE THREAD

**Issue by EliteAsian123** [EliteAsian123/YARG#47]
Some songs switch the red and yellow pads sometime (for some reason). Add support for that.

**Comment by DarkRTA** [comment]
> (for some reason)
this reason is because the pattern would be very awkward to play on a standard rb kit had it not been flipped

note that in pro drums disco beats are *not* flipped

**Comment by EliteAsian123** [comment]
That makes a lot more sense, actually. Thanks for the info!

**Comment by EliteAsian123** [comment]
Fixed in 71c6cb804361b6c06413d42106cf188d827098d7
