### ISSUE TITLE
Better Menus

### ISSUE THREAD

**Issue by EliteAsian123** [EliteAsian123/YARG#7]
Create a new main menu, settings menu, etc. and steer away from using UIDocuments.

**Comment by TheFatBastid** [comment]
You want to move to the regular gameObject type ui instead of UIElements?

**Comment by EliteAsian123** [comment]
> You want to move to the regular gameObject type ui instead of UIElements?

Yes. `UIElements` isn't in a ready enough state, unfortunately.

**Comment by TheFatBastid** [comment]
Agreed. I check in on it every beta they mention it and I'm always disappointed.
